--create sequence inventory.hibernate_sequence start 1 increment 1;

create schema callback

    create table callback.message
    (
        id           int8 generated by default as identity,
        mail         varchar(255),
        msg          varchar(255),
        name         varchar(255) not null,
        phone_number varchar(255) not null,
        constraint message_pk primary key (id)
    )