--create sequence inventory.hibernate_sequence start 1 increment 1;

create schema notes

    create table notes.note
    (
        id           int8 generated by default as identity,
        title         text,
        content       text,
        constraint note_pk primary key (id)
    )